// js/languages.js
const translations = {
    es: {
        newGame: "Nueva Partida",
        instructions: "Instrucciones",
        ranking: "Ranking",
        back: "Volver",
        continue: "Continuar",
        understood: "Entendido",
        backToMenu: "Volver al Menú",
        toTheBattle: "¡A la Batalla!",
        chooseYourName: "Elige tu Nombre",
        writeYourName: "Escribe tu nombre",
        player: "JUGADOR",
        assault: "ASALTO",
        health: "VIDA",
        power: "PODER",
        resources: "RECURSOS",
        superpower: "SUPERPODER",
        objective: "OBJETIVO:",
        objectiveText: "¡Derrota a tantos Brawlers enemigos como puedas!",
        decisions: "DECISIONES:",
        decisionsText: "En cada turno, elige uno de tus movimientos para atacar o defenderte.",
        stats: "ESTADÍSTICAS:",
        statsText: "Tu Vida, Poder y Recursos dependen del Brawler que elijas.",
        enemies: "ENEMIGOS:",
        enemiesText: "Cada asalto te enfrentarás a un nuevo Brawler aleatorio.",
        superpowerTitle: "SUPERPODER:",
        superpowerText: "Se carga con tus acciones. ¡Al 100% podrás usar un ataque devastador!",
        defeated: "¡DERROTADO!",
        defeatedReasonNoHealth: "Tu Brawler se ha quedado sin vida en combate.",
        causeOfDeath: "Causa:",
        youLasted: "Has aguantado",
        assaults: "asaltos.",
        calculatingRank: "Calculando tu posición en el ranking...",
        rankPosition: (rank) => `¡Has quedado en la <span class="font-bold text-yellow-300">${rank}ª</span> posición!`,
        scoreSaved: "Tu puntuación ha sido guardada.",
        rankingTitle: "🏆 Ranking 🏆",
        rankHeader: "#",
        nameHeader: "Nombre",
        collectiblesHeader: "💎",
        assaultsHeader: "Asaltos",
        loading: "Cargando...",
        beTheFirst: "¡Sé el primero en jugar!",
        errorLoadingRank: "Error al cargar ranking.",
        super: "SUPER",
        notEnoughResources: "¡No tienes suficientes recursos!",
        installGame: "📥 Instalar Juego",
    },
    eu: {
        newGame: "Joko Berria",
        instructions: "Argibideak",
        ranking: "Sailkapena",
        back: "Atzera",
        continue: "Jarraitu",
        understood: "Ulertuta",
        backToMenu: "Menu Nagusira Itzuli",
        toTheBattle: "Borrokarako Prest!",
        chooseYourName: "Aukeratu Zure Izena",
        writeYourName: "Idatzi zure izena",
        player: "JOKALARIA",
        assault: "ASALTOA",
        health: "BIZITZA",
        power: "INDARRA",
        resources: "BALIABIDEAK",
        superpower: "SUPERBOTEREA",
        objective: "HELBURUA:",
        objectiveText: "Garaitu ahal dituzun Brawler etsai guztiak!",
        decisions: "ERABAKIAK:",
        decisionsText: "Txanda bakoitzean, aukeratu zure mugimenduetako bat erasotzeko edo defendatzeko.",
        stats: "ESTATISTIKAK:",
        statsText: "Zure Bizitza, Indarra eta Baliabideak aukeratzen duzun Brawlerraren araberakoak dira.",
        enemies: "ETSAIAK:",
        enemiesText: "Asalto bakoitzean ausazko Brawler etsai berri baten aurka borrokatuko duzu.",
        superpowerTitle: "SUPERBOTEREA:",
        superpowerText: "Zure ekintzekin kargatzen da. %100ean eraso suntsitzaile bat erabili ahal izango duzu!",
        defeated: "GARAITUA!",
        defeatedReasonNoHealth: "Zure Brawlerra bizitzarik gabe geratu da borrokan.",
        causeOfDeath: "Kausa:",
        youLasted: "Eutsi diozu",
        assaults: "asalto.",
        calculatingRank: "Zure postua kalkulatzen sailkapenean...",
        rankPosition: (rank) => `<span class="font-bold text-yellow-300">${rank}.</span> postuan geratu zara!`,
        scoreSaved: "Zure puntuazioa gorde da.",
        rankingTitle: "🏆 Sailkapena 🏆",
        rankHeader: "#",
        nameHeader: "Izena",
        collectiblesHeader: "💎",
        assaultsHeader: "Asaltoak",
        loading: "Kargatzen...",
        beTheFirst: "Izan zaitez lehena jokatzen!",
        errorLoadingRank: "Errorea sailkapena kargatzean.",
        super: "SUPER",
        notEnoughResources: "Ez duzu nahikoa baliabide!",
        installGame: "📥 Jokoa Instalatu",
    }
};

const getText = (key, ...args) => {
    if (!translations || !translations[currentLang]) return key;
    const translation = translations[currentLang][key];
    if (!translation) return key;
    return typeof translation === 'function' ? translation(...args) : translation;
};
