// Contenido para el_primo_data.js

// Añadimos los datos de El Primo al array global de personajes
window.gameCharacters.push({
    name: 'El Primo',
    img: 'avatares/el_primo.png', // Asegúrate de tener una imagen el_primo.png en la carpeta avatares
    dilemmas: [
        { description: '¡Hay muchos enemigos juntos! ¡Es el momento de mi salto!', options: [{ text: '¡SALTA!', narrative: '¡EL PRIMOOO! Cae sobre ellos. Recibes daño pero cargas mucho Súper.', effects: { vida: -20, ataque: 10, superpoder: 30 } }, { text: 'Espera y defiende', narrative: 'Aseguras la posición. Aburrido, pero seguro.', effects: { defensa: 15 } }] },
        { description: '¡Ese robot grande parece fuerte! ¡Quiero pegarle!', options: [{ text: '¡A por él!', narrative: 'Te lanzas contra el robot. Es una pelea dura que te deja herido.', effects: { vida: -25, superpoder: 25 } }, { text: 'Mejor desde lejos', narrative: 'Le disparáis desde una distancia segura.', effects: { ataque: 10 } }] },
        { description: '¡Ese francotirador me está molestando! ¡Voy a correr hacia él!', options: [{ text: '¡Ve a por él!', narrative: 'Corres hacia el francotirador. Recibes daño pero lo eliminas y cargas Súper.', effects: { vida: -20, superpoder: 20 } }, { text: 'Busca cobertura', narrative: 'Te escondes del francotirador, mejorando tu defensa.', effects: { defensa: 20, ataque: -5 } }] },
        { description: '¡El gimnasio está abierto! ¡Un entrenamiento rápido aumentará nuestro ataque!', options: [{ text: '¡A entrenar!', narrative: 'Un entrenamiento rápido. Vuestro ataque sube, pero el cansancio baja la defensa.', effects: { ataque: 20, defensa: -10 } }, { text: 'No hay tiempo', narrative: 'Decides que es mejor descansar y recuperar fuerzas.', effects: { vida: 10 } }] },
        { description: '¡Puedo levantar ese coche y lanzárselo a los enemigos!', options: [{ text: '¡Levántalo!', narrative: '¡El coche vuela por los aires y aplasta a los enemigos! Una proeza que carga Súper.', effects: { ataque: 15, superpoder: 20, vida: -5 } }, { text: 'No hagas el bruto', narrative: 'Prefieres una táctica menos llamativa y más segura.', effects: { defensa: 10 } }] },
        { description: '¡Mi Súper está listo! ¿Lo uso para saltar en medio de todos?', options: [{ text: '¡SALTO DEL TIGRE!', narrative: 'Saltas en medio de la batalla, creando el caos total.', effects: { ataque: 20, defensa: -15, superpoder: -100 } }, { text: 'Guárdalo aún', narrative: 'Decides esperar a que se junten más enemigos.', effects: { defensa: 5 } }] },
        { description: 'Hay una plataforma elevada. Podría saltar allí para tener ventaja.', options: [{ text: 'Sube a la plataforma', narrative: 'Desde arriba, tienes una visión perfecta y tu defensa mejora.', effects: { defensa: 25, ataque: -5 } }, { text: 'Quédate en el suelo', narrative: 'Prefieres luchar cara a cara en el suelo.', effects: { ataque: 10 } }] },
        { description: '¡Un compañero necesita ayuda! Puedo interceptar los disparos por él.', options: [{ text: '¡Yo te protejo!', narrative: 'Te pones delante como un escudo humano. Recibes mucho daño pero salvas a tu amigo.', effects: { vida: -30, superpoder: 20 } }, { text: '¡Esquívalo!', narrative: 'Le gritas que se mueva y siga luchando.', effects: { ataque: 5 } }] },
        { description: '¡Mira mis músculos! Puedo hacer una pose para intimidar a los enemigos.', options: [{ text: '¡Pose de victoria!', narrative: 'Tu pose es tan increíble que los enemigos se asustan y retroceden. Tu defensa sube.', effects: { defensa: 20, superpoder: 5 } }, { text: '¡Deja de posar y lucha!', narrative: 'Le dices que se centre en la batalla.', effects: { ataque: 10 } }] },
        { description: '¡Esta pared es débil! Puedo romperla para crear un nuevo camino.', options: [{ text: '¡Rompe la pared!', narrative: 'Creas un atajo que os da una ventaja de ataque sorpresa.', effects: { ataque: 20, defensa: -5 } }, { text: 'Usa la puerta', narrative: 'Prefieres no hacer ruido y usar el camino normal.', effects: { defensa: 10 } }] }
    ]
});
